config/routes.rb
ADACooks::Application.routes.draw do
  resources :cookbooks

  resources :gadgets

  resources :recipes

  resources :ingredients

  resources :users

  delete "cookbooks/:id/remove_recipe/:recipe_id" => "cookbooks#remove_recipe"

  post "cookbooks/:id/add_note/:recipe_id" => "cookbooks#add_note"

  get "/search" => "recipes#search"

  get "/search_by_ingredient" => "recipes#search_by_ingredient"

  get "/views/recipes" => "recipes#index"

  get "/supersearch" => "recipes#supersearch"

   root 'users#home'

  

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients_recipes
  has_many :ingredients, through: :ingredients_recipes 
  has_many :cookbook_recipes
  has_many :cookbooks, through: :cookbook_recipes
  has_many :gadget_recipes
  has_many :gadgets, through: :gadget_recipes

  def self.by_ingredient_name(name)
    includes(:ingredients).where(ingredients: {name: name})
  end

  def self.vegan
    where(vegan: true)
  end

  def self.search(search_term)
    if search_term
      includes(:ingredients).where("(recipes.name) LIKE :s OR ingredients.name LIKE :s", s: "%#{search_term.downcase}%")
    else
      all
    end
  end

end

app/controllers/recipes_controller.rb
 class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  def search
    @recipes = Recipe.where name: params[:name]
    render :index
  end

  # def search_by_ingredient
  #   ingredient = Ingredient.find_by_name(params[:ingredient])
  #   @recipes = ingredient.recipes
  #   render :index
  # end

  def supersearch
    @recipes = Recipe.search(params[:ingredient]) 
    render :index
  end


  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @ingredients = Ingredient.all.collect{|p| [p.name, p.id]} #array of tuples of relevant info (name, id)
    @gadgets = Gadget.all.collect{|p| [p.name, p.id]}
  end

  # GET /recipes/1/edit
  def edit
     @ingredients = Ingredient.all.collect{|p| [p.name, p.id]}
     @gadgets = Gadget.all.collect{|p| [p.name, p.id]}
    #  @recipe = Recipe.where(id:)
    #  params[:recipe][:ingredients].each do |ingredient_id|
    #   next if ingredient_id.to_i == 0
    #   ingredient = Ingredient.find(ingredient_id.to_i)
    #   @recipe.ingredients << ingredient
    # end
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    params[:recipe][:ingredients].each do |ingredient_id|
      next if ingredient_id.to_i == 0
      ingredient = Ingredient.find(ingredient_id.to_i)
      @recipe.ingredients << ingredient
    end
    params[:recipe][:gadgets].each do |gadget_id|
      next if gadget_id.to_i == 0
      gadget = Gadget.find(gadget_id.to_i)
      @recipe.gadgets << gadget
    end
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        params[:recipe][:ingredients].each do |ingredient_id|
          next if ingredient_id.to_i == 0
          ingredient = Ingredient.find(ingredient_id.to_i)
          @recipe.ingredients << ingredient
      end
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :user_id, :vegetarian, :soy, :gluten, :dairy, :vegan, :ingredients=>{}, :gadgets=>{})
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :vegetarian %><br>
    <%= f.check_box :vegetarian %>
  </div>
  <div class="field">
    <%= f.label :vegan %><br>
    <%= f.check_box :vegan %>
  </div>
  <div class="field">
    <%= f.label :gluten %><br>
    <%= f.check_box :gluten %>
  </div>
  <div class="field">
    <%= f.label :soy %><br>
    <%= f.check_box :soy %>
  </div>
    <div class="field">
    <%= f.label :dairy %><br>
    <%= f.check_box :dairy %>
  </div>

  <label><strong>Choose Ingredients:</strong></label><br>
  <%= f.select(:ingredients, @ingredients, {}, {:multiple => true}) %><br>
  <label><strong>Choose Gadgets:</strong></label><br>
  <%= f.select(:gadgets, @gadgets, {}, {:multiple => true}) %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<div class= "recipe_index">
  <h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>  
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.user_id %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<div class="recipe_container">
  <p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @recipe.user_id %>
</p>

<p>
  <strong>Vegetarian:</strong>
  <%= @recipe.vegetarian %>
</p>
<p>
  <strong>Vegan:</strong>
  <%= @recipe.vegan %>
</p>
<p>
  <strong>Dairy:</strong>
  <%= @recipe.dairy %>
</p>
<p>
  <strong>Soy:</strong>
  <%= @recipe.soy %>
</p>
<p>
  <strong>Gluten:</strong>
  <%= @recipe.gluten %>
</p>

<p>
  <strong>Ingredients:</strong>
  <ul>
  <% @recipe.ingredients.each do |ingredient|%>
  <li><%= ingredient.name %></li>
  <% end %>
  </ul>
</p>

<p>
  <strong>Gadgets:</strong>
  <ul>
  <% @recipe.gadgets.each do |gadget|%>
  <li><%= gadget.name %></li>
  <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>
</div>