config/routes.rb
ADACooks::Application.routes.draw do
  resources :cookbooks

  resources :gadgets

  resources :recipes

  resources :ingredients

  resources :users

  delete "cookbooks/:id/remove_recipe/:recipe_id" => "cookbooks#remove_recipe"

  post "cookbooks/:id/add_note/:recipe_id" => "cookbooks#add_note"

  get "/search" => "recipes#search"

  get "/search_by_ingredient" => "recipes#search_by_ingredient"

  get "/views/recipes" => "recipes#index"

  get "/supersearch" => "recipes#supersearch"

   root 'users#home'

  

end

app/models/cookbook.rb
class Cookbook < ActiveRecord::Base
  has_many :cookbook_recipes
  has_many :recipes, through: :cookbook_recipes
  validates_uniqueness_of :name, :case_sensitive => false
end

app/controllers/cookbooks_controller.rb
class CookbooksController < ApplicationController
  before_action :set_cookbook, only: [:show, :edit, :update, :destroy]

  # GET /cookbooks
  # GET /cookbooks.json
  def index
    @cookbooks = Cookbook.all
  end

  # GET /cookbooks/1
  # GET /cookbooks/1.json
  def show
  end

  # GET /cookbooks/new
  def new
    @cookbook = Cookbook.new
    @recipes = Ingredient.all.collect{|p| [p.name, p.id]}
  end

  # GET /cookbooks/1/edit
  def edit
    @recipes = Recipe.all.collect{|p| [p.name, p.id]}
  end

  # POST /cookbooks
  # POST /cookbooks.json
  def create
    @cookbook = Cookbook.new(cookbook_params)
    params[:cookbook][:recipes].each do |recipe_id|
      next if recipe_id.to_i == 0
      recipe = Recipe.find(recipe_id.to_i)
      @cookbook.recipes << recipe
    end

    respond_to do |format|
      if @cookbook.save
        format.html { redirect_to @cookbook, notice: 'Cookbook was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cookbook }
      else
        format.html { render action: 'new' }
        format.json { render json: @cookbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cookbooks/1
  # PATCH/PUT /cookbooks/1.json
  def update
    respond_to do |format|
      if @cookbook.update(cookbook_params)
        params[:cookbook][:recipes].each do |recipe_id|
          next if recipe_id.to_i == 0
          recipe = Recipe.find(recipe_id.to_i)
          @cookbook.recipes << recipe
      end
        format.html { redirect_to @cookbook, notice: 'Cookbook was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cookbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cookbooks/1
  # DELETE /cookbooks/1.json
  def destroy
    @cookbook.destroy
    respond_to do |format|
      format.html { redirect_to cookbooks_url }
      format.json { head :no_content }
    end
  end

  def remove_recipe
    r = CookbookRecipe.find_by_cookbook_id_and_recipe_id(params[:id], params[:recipe_id])
    r.destroy
    redirect_to cookbook_path(params[:id])
  end

  def add_note
    r = CookbookRecipe.find_by_cookbook_id_and_recipe_id(params[:id], params[:recipe_id])
    r.notes = params[:cookbook_recipe][:notes]
    r.save!

    redirect_to cookbook_path(params[:id])
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cookbook
      @cookbook = Cookbook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cookbook_params
      params.require(:cookbook).permit(:name, :user_id, :recipes =>{})
    end
end

app/helpers/cookbooks_helper.rb
module CookbooksHelper
end

app/views/cookbooks/_form.html.erb
<%= form_for(@cookbook) do |f| %>
  <% if @cookbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cookbook.errors.count, "error") %> prohibited this cookbook from being saved:</h2>

      <ul>
      <% @cookbook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
 
 <%= f.select(:recipes, @recipes, {}, {:multiple => true}) %>

  <div class="actions">
    <%= f.submit %>
  </div>



<% end %>

app/views/cookbooks/edit.html.erb
<h1>Editing cookbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @cookbook %> |
<%= link_to 'Back', cookbooks_path %>

app/views/cookbooks/index.html.erb
<div class= "cookbook_index_container">
  <div class="cookbook_index">
      <h1>Cookbooks</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>User</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @cookbooks.each do |cookbook| %>
          <tr>
            <td><%= cookbook.name %></td>
            <td><%= cookbook.user_id %></td>
            <td><%= link_to 'Show', cookbook %></td>
            <td><%= link_to 'Edit', edit_cookbook_path(cookbook) %></td>
            <td><%= link_to 'Destroy', cookbook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Cookbook', new_cookbook_path %>
  </div>
</div>

app/views/cookbooks/new.html.erb
<h1>New cookbook</h1>

<%= render 'form' %>

<%= link_to 'Back', cookbooks_path %>

app/views/cookbooks/show.html.erb
<p id="notice"><%= notice %></p>

<div class="cookbook_container">
  <p>
  <strong>Name:</strong>
  <%= @cookbook.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @cookbook.user_id %>
</p>
<p>
  <strong>Recipes:</strong><br>
<!--   <ol> -->
<table>
  <% @cookbook.recipes.each do |recipe|%>
    <tr class="cookbook-table">
      <td><%= recipe.name %></td>
      <td><%= link_to 'Delete', "/cookbooks/#{@cookbook.id}/remove_recipe/#{recipe.id}", method: :delete, data: {confirm: "Are you sure you want to remove this recipe?"}%></li></td>
      <td><%= link_to 'Add Note', "/cookbooks/:id/add_note/:recipe_id", method: :post %>

      <%= form_for :cookbook_recipe, url: "/cookbooks/#{@cookbook.id}/add_note/#{recipe.id}" do |p| %>
         <%= p.label :notes %><br />
         <%= p.text_area :notes %>

         <%= submit_tag("Update") %>
      <%end%> </td>
   </tr>
  <% end %>

  <!-- </ol> -->
</table>
</p>

</div>

<%= link_to 'Edit', edit_cookbook_path(@cookbook) %> |
<%= link_to 'Back', cookbooks_path %>