config/routes.rb
ADACooks::Application.routes.draw do
  resources :cookbooks

  resources :gadgets

  resources :recipes

  resources :ingredients

  resources :users

  delete "cookbooks/:id/remove_recipe/:recipe_id" => "cookbooks#remove_recipe"

  post "cookbooks/:id/add_note/:recipe_id" => "cookbooks#add_note"

  get "/search" => "recipes#search"

  get "/search_by_ingredient" => "recipes#search_by_ingredient"

  get "/views/recipes" => "recipes#index"

  get "/supersearch" => "recipes#supersearch"

   root 'users#home'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ADACooks</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %> 
  <link href='http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps' rel='stylesheet' type='text/css'>
  <!-- can add style sheet here just as "sheet" , with actual .css file stored in app/assets/stylesheets folder, but the default layout is is scaffolds.css.scss-->
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <header>
    <div id="nav-bar">
      <h1 id="title-header">ADA Cooks</h1>
      <%= link_to 'Recipes', recipes_path %>
      <%= link_to 'Cookbook', cookbooks_path %>
      <%= link_to 'Ingredients', ingredients_path %>
      <%= link_to 'Users', users_path %>
     
     <div id="search-bar">
        <div id="ingredient_search">
          <%= form_tag("/supersearch", method: "get") do %>
            <%= label_tag("Find recipe by ingredient!") %>
            <%= text_field_tag(:ingredient, params[:ingredient]) %>
            <%= submit_tag("Search") %>
          <% end %>
        </div>
     </div>
   </div>
   
  </header>

<%= yield %>

</body>
</html>